name: ChangeTask

on: workflow_dispatch

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:     
            - name: ServiceNow DevOps Change Automation
            # You may pin to the exact commit or the version.
            # uses: ServiceNow/servicenow-devops-change@0f57435999463cc1dea44bde4f5eca9879474b85
              uses: ServiceNow/servicenow-devops-change@v1.38.0
              with:
                  # ServiceNow Instance URL
                  instance-url: ${{ secrets.SN_INSTANCE_URL }}
                  # Devops Integration User Name
                  devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                  # Devops Integration User Password
                  devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                  # Orchestration Tool Id
                  tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                  # Display Name of the Job
                  job-name: 'Deploy'
                  # Github Context
                  context-github: ${{ toJSON(github) }}
                  # The max. time in seconds to wait until the action should fail.
                  timeout: 3600 # optional, default is 3600
                  # The time in seconds to wait between trying the API.
                  interval: 100 # optional, default is 100
                  # The customized inputs to create change with the requested details.
                  change-request: '{"setCloseCode":"true","attributes":{"short_description":"FIRST CR","description":"Automated Software Deployment."}}'
            - name: Run deployment scripts
              run: echo Completed Deployment   
